name: Cigars4Soul
favicon: null
layout_spectrum: 0.51876
typography_spectrum: 0.52489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fff8f0'
    - '#b68543'
    - '#82470f'
    - '#ae081d'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
